<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Squad.Sim\Squad.Sim.csproj" />
    <ProjectReference Include="..\Squad.Bots\Squad.Bots.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.153.1" />
  </ItemGroup>
</Project>
